name: 📦 Release
on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.release_id.outputs.result }}
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
      - name: 🦀 Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: 🪚 Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: 🎚️ Install tomato-toml
        run: cargo install tomato-toml
      - name: 🕸️ Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: 🥾 Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: 🎁 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: 🚀 Install Node dependencies
        run: pnpm i --frozen-lockfile
      - name: 🚀 Install Semantic-Release
        run: pnpm i -D semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec
      - name: 📦 Create Release
        id: semantic
        run: "npx semantic-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🏷️ Get release id
        id: release_id
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.getLatestRelease({ 
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "${{ steps.semantic.outputs.gitTag }}"
            })

            return data.id

  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            rust-targets: x86_64-pc-windows-msvc
            tauri-target: x86_64-pc-windows-msvc
          - platform: macos-latest
            rust-targets: x86_64-apple-darwin,aarch64-apple-darwin
            tauri-target: universal-apple-darwin
    runs-on: ${{ matrix.platform }}
    needs:
      - release
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
      - name: 🦀 Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: 🪚 Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
          targets: ${{ matrix.rust-targets }}
      - name: 🕸️ Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
      - name: 🥾 Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: 🎁 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: 🚀 Install Node dependencies
        run: pnpm i --frozen-lockfile
      - name: 🚧 Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          #APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          #APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          #APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          #APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        with:
          releaseId: ${{ needs.release.outputs.release_id }}
          tagName: __VERSION__
          args: --target ${{ matrix.tauri-target }}
          releaseDraft: false
          prerelease: false
          tauriScript: pnpm tauri
